// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: protos/public.proto

package public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PublicService_Create_FullMethodName        = "/protos.PublicService/Create"
	PublicService_Update_FullMethodName        = "/protos.PublicService/Update"
	PublicService_Delete_FullMethodName        = "/protos.PublicService/Delete"
	PublicService_GetById_FullMethodName       = "/protos.PublicService/GetById"
	PublicService_IsValidPublic_FullMethodName = "/protos.PublicService/IsValidPublic"
)

// PublicServiceClient is the client API for PublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicServiceClient interface {
	Create(ctx context.Context, in *PublicCreate, opts ...grpc.CallOption) (*Public, error)
	Update(ctx context.Context, in *PublicUpdate, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *PublicDelete, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *PublicById, opts ...grpc.CallOption) (*Public, error)
	IsValidPublic(ctx context.Context, in *ValidPublicReq, opts ...grpc.CallOption) (*ValidPublicRes, error)
}

type publicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicServiceClient(cc grpc.ClientConnInterface) PublicServiceClient {
	return &publicServiceClient{cc}
}

func (c *publicServiceClient) Create(ctx context.Context, in *PublicCreate, opts ...grpc.CallOption) (*Public, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Public)
	err := c.cc.Invoke(ctx, PublicService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) Update(ctx context.Context, in *PublicUpdate, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) Delete(ctx context.Context, in *PublicDelete, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, PublicService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) GetById(ctx context.Context, in *PublicById, opts ...grpc.CallOption) (*Public, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Public)
	err := c.cc.Invoke(ctx, PublicService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) IsValidPublic(ctx context.Context, in *ValidPublicReq, opts ...grpc.CallOption) (*ValidPublicRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidPublicRes)
	err := c.cc.Invoke(ctx, PublicService_IsValidPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServiceServer is the server API for PublicService service.
// All implementations must embed UnimplementedPublicServiceServer
// for forward compatibility
type PublicServiceServer interface {
	Create(context.Context, *PublicCreate) (*Public, error)
	Update(context.Context, *PublicUpdate) (*Void, error)
	Delete(context.Context, *PublicDelete) (*Void, error)
	GetById(context.Context, *PublicById) (*Public, error)
	IsValidPublic(context.Context, *ValidPublicReq) (*ValidPublicRes, error)
	mustEmbedUnimplementedPublicServiceServer()
}

// UnimplementedPublicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPublicServiceServer struct {
}

func (UnimplementedPublicServiceServer) Create(context.Context, *PublicCreate) (*Public, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPublicServiceServer) Update(context.Context, *PublicUpdate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPublicServiceServer) Delete(context.Context, *PublicDelete) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPublicServiceServer) GetById(context.Context, *PublicById) (*Public, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedPublicServiceServer) IsValidPublic(context.Context, *ValidPublicReq) (*ValidPublicRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValidPublic not implemented")
}
func (UnimplementedPublicServiceServer) mustEmbedUnimplementedPublicServiceServer() {}

// UnsafePublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicServiceServer will
// result in compilation errors.
type UnsafePublicServiceServer interface {
	mustEmbedUnimplementedPublicServiceServer()
}

func RegisterPublicServiceServer(s grpc.ServiceRegistrar, srv PublicServiceServer) {
	s.RegisterService(&PublicService_ServiceDesc, srv)
}

func _PublicService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).Create(ctx, req.(*PublicCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).Update(ctx, req.(*PublicUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).Delete(ctx, req.(*PublicDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).GetById(ctx, req.(*PublicById))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_IsValidPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).IsValidPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_IsValidPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).IsValidPublic(ctx, req.(*ValidPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicService_ServiceDesc is the grpc.ServiceDesc for PublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PublicService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PublicService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PublicService_Delete_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _PublicService_GetById_Handler,
		},
		{
			MethodName: "IsValidPublic",
			Handler:    _PublicService_IsValidPublic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/public.proto",
}
